# Generated by Django 5.1.3 on 2024-11-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='authors',
            field=models.CharField(max_length=1024),
        ),
    ]
