# Generated by Django 5.1.3 on 2024-11-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_ID', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=1024)),
                ('priority', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=1024)),
            ],
        ),
    ]
