# Generated by Django 5.1.3 on 2024-11-30 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_typetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='typetask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.typetask'),
        ),
    ]
