# Generated by Django 5.1.3 on 2024-12-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_priority_alter_typetask_type_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
